name: base 
channels:
  - conda-forge
dependencies:
  - gh-scoped-creds
  - glances
  - git-filter-repo
  - jupyterlab-myst
  - jupyter-resource-usage
  - jupyter-rsession-proxy
  - jupyter-vscode-proxy
  - jupyterlab-myst
  - mystmd
  - pypdf
  - pip
  - pip:
    - jupyter-keepalive

